import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, asaas-access-token',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Validate method
    if (req.method !== 'POST') {
      return new Response('Method not allowed', { 
        status: 405,
        headers: corsHeaders 
      })
    }

    // Create Supabase client
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Validate authentication token (security)
    const authToken = req.headers.get('asaas-access-token')
    const expectedToken = Deno.env.get('ASAAS_WEBHOOK_TOKEN')
    
    if (authToken !== expectedToken) {
      console.error('[asaas-webhook] Invalid token')
      return new Response('Unauthorized', { 
        status: 401,
        headers: corsHeaders 
      })
    }

    const body = await req.json()
    const event = body.event

    console.log('[asaas-webhook] Webhook received:', event, JSON.stringify(body, null, 2))

    switch (event) {
      // New monthly charge automatically generated by Asaas
      case 'PAYMENT_CREATED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_CREATED:', payment.id)
        
        // Find subscription by asaas_subscription_id
        const { data: assinatura } = await supabase
          .from('assinaturas')
          .select('id, cliente_id')
          .eq('asaas_subscription_id', payment.subscription)
          .single()

        if (!assinatura) {
          console.error('[asaas-webhook] Subscription not found:', payment.subscription)
          break
        }

        // Create payment record
        const { error: insertError } = await supabase.from('cobrancas').insert({
          cliente_id: assinatura.cliente_id,
          assinatura_id: assinatura.id,
          valor: payment.value,
          status: 'pending',
          descricao: payment.description,
          data_vencimento: payment.dueDate,
          asaas_payment_id: payment.id,
          link_pagamento: payment.invoiceUrl,
        })

        if (insertError) {
          console.error('[asaas-webhook] Error creating payment:', insertError)
        }

        // Update next charge date
        const nextDate = new Date(payment.dueDate)
        nextDate.setMonth(nextDate.getMonth() + 1)
        
        await supabase.from('assinaturas')
          .update({ proxima_cobranca: nextDate.toISOString().split('T')[0] })
          .eq('id', assinatura.id)

        console.log('[asaas-webhook] Payment record created successfully')

        break
      }

      // Payment confirmed (still not available)
      case 'PAYMENT_CONFIRMED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_CONFIRMED:', payment.id)
        
        await supabase.from('cobrancas')
          .update({ 
            status: 'paid',
            data_pagamento: new Date().toISOString(),
          })
          .eq('asaas_payment_id', payment.id)

        break
      }

      // Payment received (balance available)
      case 'PAYMENT_RECEIVED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_RECEIVED:', payment.id)
        
        await supabase.from('cobrancas')
          .update({ 
            status: 'paid',
            data_pagamento: new Date().toISOString(),
            forma_pagamento: payment.billingType,
          })
          .eq('asaas_payment_id', payment.id)

        break
      }

      // Payment overdue
      case 'PAYMENT_OVERDUE': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_OVERDUE:', payment.id)
        
        // Update payment status
        await supabase.from('cobrancas')
          .update({ status: 'overdue' })
          .eq('asaas_payment_id', payment.id)

        // Find subscription
        const { data: cobranca } = await supabase
          .from('cobrancas')
          .select('assinatura_id, cliente_id')
          .eq('asaas_payment_id', payment.id)
          .single()

        if (cobranca) {
          // Count overdue payments for this subscription
          const { data: overduePayments } = await supabase
            .from('cobrancas')
            .select('id')
            .eq('assinatura_id', cobranca.assinatura_id)
            .eq('status', 'overdue')
          
          const overdueCount = overduePayments?.length || 0
          
          console.log(`[asaas-webhook] Subscription has ${overdueCount} overdue payment(s)`)
          
          // Cancel subscription after 2 failed payments
          if (overdueCount >= 2) {
            console.log('[asaas-webhook] Cancelling subscription due to multiple overdue payments')
            
            // Cancel subscription
            await supabase.from('assinaturas')
              .update({ 
                status: 'cancelled',
                data_fim: new Date().toISOString()
              })
              .eq('id', cobranca.assinatura_id)
            
            // Get user_id from cliente
            const { data: cliente } = await supabase
              .from('clientes')
              .select('user_id')
              .eq('id', cobranca.cliente_id)
              .single()
            
            if (cliente) {
              // Reset to free plan limits
              await supabase.from('usuario_limites')
                .update({
                  max_assistentes: 0,
                  max_instancias_whatsapp: 1,
                  max_conversas_mes: 100,
                  max_agendamentos_mes: 50,
                  assinatura_id: null,
                  updated_at: new Date().toISOString()
                })
                .eq('user_id', cliente.user_id)
              
              console.log('[asaas-webhook] User limits reset to free plan')
            }
          } else if (overdueCount === 1) {
            // First overdue - just suspend access temporarily
            await supabase.from('assinaturas')
              .update({ status: 'suspended' })
              .eq('id', cobranca.assinatura_id)
            
            console.log('[asaas-webhook] Subscription suspended - first overdue payment')
          }
        }

        break
      }

      // Payment updated
      case 'PAYMENT_UPDATED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_UPDATED:', payment.id)
        
        await supabase.from('cobrancas')
          .update({ 
            valor: payment.value,
            data_vencimento: payment.dueDate,
          })
          .eq('asaas_payment_id', payment.id)

        break
      }

      // Payment refunded
      case 'PAYMENT_REFUNDED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_REFUNDED:', payment.id)
        
        await supabase.from('cobrancas')
          .update({ 
            status: 'refunded',
            data_pagamento: new Date().toISOString(),
          })
          .eq('asaas_payment_id', payment.id)

        break
      }

      // Payment deleted
      case 'PAYMENT_DELETED': {
        const payment = body.payment
        
        console.log('[asaas-webhook] PAYMENT_DELETED:', payment.id)
        
        // Update payment status
        await supabase.from('cobrancas')
          .update({ status: 'cancelled' })
          .eq('asaas_payment_id', payment.id)
        
        // Find subscription and cancel it
        const { data: cobranca } = await supabase
          .from('cobrancas')
          .select('assinatura_id, cliente_id')
          .eq('asaas_payment_id', payment.id)
          .single()

        if (cobranca) {
          // Cancel subscription
          await supabase.from('assinaturas')
            .update({ 
              status: 'cancelled',
              data_fim: new Date().toISOString()
            })
            .eq('id', cobranca.assinatura_id)
          
          // Get user_id and reset limits
          const { data: cliente } = await supabase
            .from('clientes')
            .select('user_id')
            .eq('id', cobranca.cliente_id)
            .single()
          
          if (cliente) {
            await supabase.from('usuario_limites')
              .update({
                max_assistentes: 0,
                max_instancias_whatsapp: 1,
                max_conversas_mes: 100,
                max_agendamentos_mes: 50,
                assinatura_id: null,
                updated_at: new Date().toISOString()
              })
              .eq('user_id', cliente.user_id)
            
            console.log('[asaas-webhook] Subscription cancelled and limits reset due to payment deletion')
          }
        }

        break
      }

      // Subscription created
      case 'SUBSCRIPTION_CREATED': {
        const subscription = body.subscription
        
        console.log('[asaas-webhook] SUBSCRIPTION_CREATED:', subscription.id)
        
        // Validate that it was saved correctly in database
        const { data: assinatura } = await supabase
          .from('assinaturas')
          .select('id')
          .eq('asaas_subscription_id', subscription.id)
          .single()

        if (!assinatura) {
          console.error('[asaas-webhook] Subscription not found in database:', subscription.id)
        }

        break
      }

      // Subscription updated
      case 'SUBSCRIPTION_UPDATED': {
        const subscription = body.subscription
        
        console.log('[asaas-webhook] SUBSCRIPTION_UPDATED:', subscription.id)
        
        // Map Asaas status to our database
        let status = 'active'
        if (subscription.status === 'INACTIVE') {
          status = 'inactive'
        } else if (subscription.status === 'EXPIRED') {
          status = 'cancelled'
        }

        await supabase.from('assinaturas')
          .update({ 
            status: status,
            proxima_cobranca: subscription.nextDueDate,
          })
          .eq('asaas_subscription_id', subscription.id)

        break
      }

      // Subscription inactivated (suspended for non-payment)
      case 'SUBSCRIPTION_INACTIVATED': {
        const subscription = body.subscription
        
        console.log('[asaas-webhook] SUBSCRIPTION_INACTIVATED:', subscription.id)
        
        // Get subscription data
        const { data: assinatura } = await supabase
          .from('assinaturas')
          .select('cliente_id')
          .eq('asaas_subscription_id', subscription.id)
          .single()
        
        if (assinatura) {
          // Update subscription status
          await supabase.from('assinaturas')
            .update({ status: 'inactive' })
            .eq('asaas_subscription_id', subscription.id)
          
          // Get user_id and reset limits
          const { data: cliente } = await supabase
            .from('clientes')
            .select('user_id')
            .eq('id', assinatura.cliente_id)
            .single()
          
          if (cliente) {
            await supabase.from('usuario_limites')
              .update({
                max_assistentes: 0,
                max_instancias_whatsapp: 1,
                max_conversas_mes: 100,
                max_agendamentos_mes: 50,
                assinatura_id: null,
                updated_at: new Date().toISOString()
              })
              .eq('user_id', cliente.user_id)
            
            console.log('[asaas-webhook] User access suspended - limits reset to free plan')
          }
        }

        break
      }

      // Subscription deleted
      case 'SUBSCRIPTION_DELETED': {
        const subscription = body.subscription
        
        console.log('[asaas-webhook] SUBSCRIPTION_DELETED:', subscription.id)
        
        await supabase.from('assinaturas')
          .update({ 
            status: 'cancelled',
            data_fim: new Date().toISOString(),
          })
          .eq('asaas_subscription_id', subscription.id)

        break
      }

      default:
        console.log('[asaas-webhook] Unhandled event:', event)
    }

    return new Response(
      JSON.stringify({ received: true }), 
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    )

  } catch (error) {
    console.error('[asaas-webhook] Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }), 
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    )
  }
})
